import {
  ArrowLeftRightIcon,
  HeadsetIcon,
  KeyIcon,
  SquareCheckBigIcon,
  UserIcon,
} from "lucide-react";
import {
  CATEGORY_CONFIG,
  DEPARTMENT_CONFIG,
  EMPLOYEE_CONFIG,
  KEY_INFORMATION_GROUP_CONFIG,
  KEY_INFORMATION_GROUP_PERMISSION_CONFIG,
  KEY_INFORMATION_TAG_CONFIG,
  NOTIFICATION_GROUP_CONFIG,
  ORGANIZATION_CONFIG,
  ORGANIZATION_PERMISSION_CONFIG,
  PROFILE_CONFIG,
  PROJECT_CONFIG,
  PROJECT_TAG_CONFIG,
  ROLE_CONFIG,
  SERVICE_GROUP_CONFIG,
  SERVICE_GROUP_PERMISSION_CONFIG,
  SERVICE_TAG_CONFIG,
  TASK_CONFIG,
  TRANSACTION_CONFIG,
  TRANSACTION_GROUP_CONFIG,
  TRANSACTION_GROUP_PERMISSION_CONFIG,
  TRANSACTION_TAG_CONFIG,
  USER_NOTIFICATION_GROUP_CONFIG,
} from "./PageConfigDetails";

const PAGE_CONFIG = {
  ...TRANSACTION_CONFIG,
  ...ROLE_CONFIG,
  ...EMPLOYEE_CONFIG,
  ...PROFILE_CONFIG,
  ...DEPARTMENT_CONFIG,
  ...TRANSACTION_GROUP_CONFIG,
  ...TRANSACTION_GROUP_PERMISSION_CONFIG,
  ...SERVICE_GROUP_CONFIG,
  ...SERVICE_GROUP_PERMISSION_CONFIG,
  ...KEY_INFORMATION_GROUP_CONFIG,
  ...KEY_INFORMATION_GROUP_PERMISSION_CONFIG,
  ...ORGANIZATION_CONFIG,
  ...ORGANIZATION_PERMISSION_CONFIG,
  ...CATEGORY_CONFIG,
  ...TRANSACTION_TAG_CONFIG,
  ...SERVICE_TAG_CONFIG,
  ...KEY_INFORMATION_TAG_CONFIG,
  ...PROJECT_TAG_CONFIG,
  ...NOTIFICATION_GROUP_CONFIG,
  ...USER_NOTIFICATION_GROUP_CONFIG,
  ...PROJECT_CONFIG,
  ...TASK_CONFIG,
};

const SESSION_KEY_PAGES: Set<string> = new Set([
  PAGE_CONFIG.TRANSACTION.name,
  PAGE_CONFIG.TRANSACTION_GROUP.name,
  PAGE_CONFIG.SERVICE_GROUP.name,
  PAGE_CONFIG.KEY_INFORMATION_GROUP.name,
  PAGE_CONFIG.ORGANIZATION.name,
  PAGE_CONFIG.CATEGORY.name,
  PAGE_CONFIG.TRANSACTION_TAG.name,
  PAGE_CONFIG.SERVICE_TAG.name,
  PAGE_CONFIG.KEY_INFORMATION_TAG.name,
  PAGE_CONFIG.PROJECT_TAG.name,
  PAGE_CONFIG.NOTIFICATION_GROUP.name,
  PAGE_CONFIG.PROJECT.name,
]);

const DECRYPT_FIELDS = {
  TRANSACTION_GROUP: ["name", "description"],
  SERVICE_GROUP: ["name", "description"],
  KEY_INFORMATION_GROUP: ["name", "description"],
  ORGANIZATION: ["logo", "name"],
  CATEGORY: ["description", "name"],
  TAG: ["colorCode", "name"],
  NOTIFICATION_GROUP: ["name", "description"],
  PROJECT: ["logo", "name", "note", "organization.name", "tag.colorCode"],
  TASK: ["name", "note", "document"],
};

const SIDEBAR_MENUS = [
  {
    name: "Quản lý giao dịch",
    icon: <ArrowLeftRightIcon size={20} />,
    items: [
      PAGE_CONFIG.TRANSACTION,
      PAGE_CONFIG.TRANSACTION_GROUP,
      PAGE_CONFIG.CATEGORY,
      PAGE_CONFIG.TRANSACTION_TAG,
    ],
  },
  {
    name: "Quản lý dịch vụ",
    icon: <HeadsetIcon size={20} />,
    items: [
      PAGE_CONFIG.SERVICE_GROUP,
      PAGE_CONFIG.NOTIFICATION_GROUP,
      PAGE_CONFIG.SERVICE_TAG,
    ],
  },
  {
    name: "Quản lý key",
    icon: <KeyIcon size={20} />,
    items: [PAGE_CONFIG.KEY_INFORMATION_GROUP, PAGE_CONFIG.KEY_INFORMATION_TAG],
  },
  {
    name: "Quản lý ghi chú",
    icon: <SquareCheckBigIcon size={20} />,
    items: [
      PAGE_CONFIG.ORGANIZATION,
      PAGE_CONFIG.PROJECT,
      PAGE_CONFIG.PROJECT_TAG,
    ],
  },
  {
    name: "Quản lý người dùng",
    icon: <UserIcon size={20} />,
    items: [PAGE_CONFIG.EMPLOYEE, PAGE_CONFIG.ROLE, PAGE_CONFIG.DEPARTMENT],
  },
];

export { PAGE_CONFIG, SIDEBAR_MENUS, SESSION_KEY_PAGES, DECRYPT_FIELDS };
